services:
  server_gateway:
    build:
      context: . 
      dockerfile: ./apps/gateway/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./apps/gateway/.env
      - ./.env
  server_auth:
    build:
      context: . 
      dockerfile: ./apps/auth/Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - ./apps/auth/.env
      - ./.env
  server_event:
    build:
      context: . 
      dockerfile: ./apps/event/Dockerfile
    ports:
      - "5002:5002"
    env_file:
      - ./apps/event/.env
      - ./.env
  db_auth:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: auth
    ports:
      - "27017:27017"
    volumes:
      - db_auth:/data/db
  db_event:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: event
    ports:
      - "27018:27017"
    volumes:
      - db_event:/data/db

volumes:
  db_auth:
    driver: local
  db_event:
    driver: local